name: hyp3-sdk
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For packaging, and testing
  - python-build
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - jupyter
  - setuptools>=61
  - setuptools_scm>=6.2
  - pytest
  - pytest-cov
  - responses
  # For running
  - python-dateutil
  - requests
  - tqdm
  - urllib3
